//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAggregator.Web.DatabaseManagerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DatabaseManagerService.IDatabaseManagerService")]
    public interface IDatabaseManagerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManagerService/CreateExternalShipment", ReplyAction="http://tempuri.org/IDatabaseManagerService/CreateExternalShipmentResponse")]
        void CreateExternalShipment();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManagerService/CreateExternalShipment", ReplyAction="http://tempuri.org/IDatabaseManagerService/CreateExternalShipmentResponse")]
        System.Threading.Tasks.Task CreateExternalShipmentAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManagerService/CreateGovernmentPurchases", ReplyAction="http://tempuri.org/IDatabaseManagerService/CreateGovernmentPurchasesResponse")]
        void CreateGovernmentPurchases();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManagerService/CreateGovernmentPurchases", ReplyAction="http://tempuri.org/IDatabaseManagerService/CreateGovernmentPurchasesResponse")]
        System.Threading.Tasks.Task CreateGovernmentPurchasesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManagerService/CreateFullGovernmentPurchases", ReplyAction="http://tempuri.org/IDatabaseManagerService/CreateFullGovernmentPurchasesResponse")]
        void CreateFullGovernmentPurchases();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManagerService/CreateFullGovernmentPurchases", ReplyAction="http://tempuri.org/IDatabaseManagerService/CreateFullGovernmentPurchasesResponse")]
        System.Threading.Tasks.Task CreateFullGovernmentPurchasesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManagerService/RunGovernmentSegmentShipmentJob", ReplyAction="http://tempuri.org/IDatabaseManagerService/RunGovernmentSegmentShipmentJobRespons" +
            "e")]
        void RunGovernmentSegmentShipmentJob();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManagerService/RunGovernmentSegmentShipmentJob", ReplyAction="http://tempuri.org/IDatabaseManagerService/RunGovernmentSegmentShipmentJobRespons" +
            "e")]
        System.Threading.Tasks.Task RunGovernmentSegmentShipmentJobAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManagerService/CalcAveragePrice", ReplyAction="http://tempuri.org/IDatabaseManagerService/CalcAveragePriceResponse")]
        void CalcAveragePrice();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManagerService/CalcAveragePrice", ReplyAction="http://tempuri.org/IDatabaseManagerService/CalcAveragePriceResponse")]
        System.Threading.Tasks.Task CalcAveragePriceAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDatabaseManagerServiceChannel : DataAggregator.Web.DatabaseManagerService.IDatabaseManagerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DatabaseManagerServiceClient : System.ServiceModel.ClientBase<DataAggregator.Web.DatabaseManagerService.IDatabaseManagerService>, DataAggregator.Web.DatabaseManagerService.IDatabaseManagerService {
        
        public DatabaseManagerServiceClient() {
        }
        
        public DatabaseManagerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DatabaseManagerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabaseManagerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabaseManagerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateExternalShipment() {
            base.Channel.CreateExternalShipment();
        }
        
        public System.Threading.Tasks.Task CreateExternalShipmentAsync() {
            return base.Channel.CreateExternalShipmentAsync();
        }
        
        public void CreateGovernmentPurchases() {
            base.Channel.CreateGovernmentPurchases();
        }
        
        public System.Threading.Tasks.Task CreateGovernmentPurchasesAsync() {
            return base.Channel.CreateGovernmentPurchasesAsync();
        }
        
        public void CreateFullGovernmentPurchases() {
            base.Channel.CreateFullGovernmentPurchases();
        }
        
        public System.Threading.Tasks.Task CreateFullGovernmentPurchasesAsync() {
            return base.Channel.CreateFullGovernmentPurchasesAsync();
        }
        
        public void RunGovernmentSegmentShipmentJob() {
            base.Channel.RunGovernmentSegmentShipmentJob();
        }
        
        public System.Threading.Tasks.Task RunGovernmentSegmentShipmentJobAsync() {
            return base.Channel.RunGovernmentSegmentShipmentJobAsync();
        }
        
        public void CalcAveragePrice() {
            base.Channel.CalcAveragePrice();
        }
        
        public System.Threading.Tasks.Task CalcAveragePriceAsync() {
            return base.Channel.CalcAveragePriceAsync();
        }
    }
}
